/**
 * Auto-generated by `supabase gen types typescript`.
 * This is a hand-written stub mirroring the SQL migration so the project
 * type-checks before you run codegen against your Supabase project.
 */
export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

export type OrderStatus = 'NEW' | 'CONFIRMED' | 'SHIPPED' | 'COMPLETED' | 'CANCELLED';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          role: 'admin';
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: 'admin';
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
        Relationships: [];
      };
      streamers: {
        Row: {
          id: string;
          name: string;
          ref_code: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          ref_code: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['streamers']['Insert']>;
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          customer_name: string;
          customer_phone: string;
          product_name: string;
          quantity: number;
          amount: number;
          status: OrderStatus;
          notes: string | null;
          streamer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          customer_phone: string;
          product_name: string;
          quantity?: number;
          amount?: number;
          status?: OrderStatus;
          notes?: string | null;
          streamer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'orders_streamer_id_fkey';
            columns: ['streamer_id'];
            referencedRelation: 'streamers';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      streamer_stats: {
        Row: {
          id: string;
          name: string;
          ref_code: string;
          is_active: boolean;
          created_at: string;
          orders_count: number;
          revenue: number;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_admin: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: { order_status: OrderStatus };
    CompositeTypes: Record<string, never>;
  };
}
